string = str(input("Enter the input:"))
print("ALL CAPS")
print(string.upper())
print("all small")
print(string.lower())
print("Title")
print(string.title())
print("Capitalize")
print(string.capitalize())